export const CLASSES = [
  {
    id: 1,
    name: 'Lengua y Literatura',
    schedule: 'Lun, Mié, Vie 10:00-11:30',
    room: 'Aula 201',
    studentCount: 28,
    semester: '2024-1',
    color: 'bg-blue-500',
  },
  {
    id: 2,
    name: 'Matemáticas',
    schedule: 'Mar, Jue 14:00-15:30',
    room: 'Lab 105',
    studentCount: 22,
    semester: '2024-1',
    color: 'bg-purple-500',
  },
  {
    id: 3,
    name: 'Ciencias Naturales',
    schedule: 'Lun, Mié 16:00-17:30',
    room: 'Lab 203',
    studentCount: 25,
    semester: '2024-1',
    color: 'bg-green-500',
  },
  {
    id: 4,
    name: 'Ciencias Sociales',
    schedule: 'Lun, Mié 16:00-17:30',
    room: 'Lab 2404',
    studentCount: 30,
    semester: '2024-1',
    color: 'bg-red-500',
  },
];

export const STUDENTS = {
  1: [
    {
      id: 1,
      name: 'Ana García López',
      email: 'ana.garcia@email.com',
      avatar: '/placeholder.svg?height=40&width=40',
      grade: 'A',
      attendance: '95%',
    },
    {
      id: 2,
      name: 'Carlos Rodríguez',
      email: 'carlos.rodriguez@email.com',
      avatar: '/placeholder.svg?height=40&width=40',
      grade: 'B+',
      attendance: '88%',
    },
    {
      id: 3,
      name: 'María Fernández',
      email: 'maria.fernandez@email.com',
      avatar: '/placeholder.svg?height=40&width=40',
      grade: 'A-',
      attendance: '92%',
    },
    {
      id: 4,
      name: 'José Martínez',
      email: 'jose.martinez@email.com',
      avatar: '/placeholder.svg?height=40&width=40',
      grade: 'B',
      attendance: '85%',
    },
    {
      id: 5,
      name: 'Laura Sánchez',
      email: 'laura.sanchez@email.com',
      avatar: '/placeholder.svg?height=40&width=40',
      grade: 'A+',
      attendance: '98%',
    },
    {
      id: 6,
      name: 'Diego Morales',
      email: 'diego.morales@email.com',
      avatar: '/placeholder.svg?height=40&width=40',
      grade: 'B-',
      attendance: '82%',
    },
    {
      id: 7,
      name: 'Carmen Ruiz',
      email: 'carmen.ruiz@email.com',
      avatar: '/placeholder.svg?height=40&width=40',
      grade: 'A',
      attendance: '94%',
    },
    {
      id: 8,
      name: 'Roberto Silva',
      email: 'roberto.silva@email.com',
      avatar: '/placeholder.svg?height=40&width=40',
      grade: 'B+',
      attendance: '90%',
    },
  ],
  2: [
    {
      id: 9,
      name: 'Elena Vargas',
      email: 'elena.vargas@email.com',
      avatar: '/placeholder.svg?height=40&width=40',
      grade: 'A-',
      attendance: '91%',
    },
    {
      id: 10,
      name: 'Miguel Torres',
      email: 'miguel.torres@email.com',
      avatar: '/placeholder.svg?height=40&width=40',
      grade: 'B',
      attendance: '87%',
    },
    {
      id: 11,
      name: 'Patricia Jiménez',
      email: 'patricia.jimenez@email.com',
      avatar: '/placeholder.svg?height=40&width=40',
      grade: 'A',
      attendance: '96%',
    },
    {
      id: 12,
      name: 'Fernando Castro',
      email: 'fernando.castro@email.com',
      avatar: '/placeholder.svg?height=40&width=40',
      grade: 'B+',
      attendance: '89%',
    },
    {
      id: 13,
      name: 'Isabel Herrera',
      email: 'isabel.herrera@email.com',
      avatar: '/placeholder.svg?height=40&width=40',
      grade: 'A+',
      attendance: '97%',
    },
    {
      id: 14,
      name: 'Andrés Mendoza',
      email: 'andres.mendoza@email.com',
      avatar: '/placeholder.svg?height=40&width=40',
      grade: 'B-',
      attendance: '84%',
    },
  ],
  3: [
    {
      id: 9,
      name: 'Elena Vargas',
      email: 'elena.vargas@email.com',
      avatar: '/placeholder.svg?height=40&width=40',
      grade: 'A-',
      attendance: '91%',
    },
    {
      id: 10,
      name: 'Miguel Torres',
      email: 'miguel.torres@email.com',
      avatar: '/placeholder.svg?height=40&width=40',
      grade: 'B',
      attendance: '87%',
    },
    {
      id: 11,
      name: 'Patricia Jiménez',
      email: 'patricia.jimenez@email.com',
      avatar: '/placeholder.svg?height=40&width=40',
      grade: 'A',
      attendance: '96%',
    },
    {
      id: 12,
      name: 'Fernando Castro',
      email: 'fernando.castro@email.com',
      avatar: '/placeholder.svg?height=40&width=40',
      grade: 'B+',
      attendance: '89%',
    },
    {
      id: 13,
      name: 'Isabel Herrera',
      email: 'isabel.herrera@email.com',
      avatar: '/placeholder.svg?height=40&width=40',
      grade: 'A+',
      attendance: '97%',
    },
    {
      id: 14,
      name: 'Andrés Mendoza',
      email: 'andres.mendoza@email.com',
      avatar: '/placeholder.svg?height=40&width=40',
      grade: 'B-',
      attendance: '84%',
    },
  ],
};
