export const studentsData = [
  {
    id: 1,
    name: 'Ana García',
    email: 'ana.garcia@escuela.com',
    avatar: 'AG',
    currentGrades: {
      math: 85,
      science: 92,
      spanish: 78,
      english: 88,
      history: 90,
    },
    monthlyProgress: [
      {
        month: 'Ene',
        math: 80,
        science: 88,
        spanish: 75,
        english: 85,
        history: 87,
      },
      {
        month: 'Feb',
        math: 82,
        science: 89,
        spanish: 76,
        english: 86,
        history: 88,
      },
      {
        month: 'Mar',
        math: 84,
        science: 90,
        spanish: 77,
        english: 87,
        history: 89,
      },
      {
        month: 'Abr',
        math: 85,
        science: 91,
        spanish: 78,
        english: 88,
        history: 90,
      },
      {
        month: 'May',
        math: 85,
        science: 92,
        spanish: 78,
        english: 88,
        history: 90,
      },
    ],
    assignments: [
      {
        name: 'Examen 1',
        math: 88,
        science: 95,
        spanish: 80,
        english: 90,
        history: 92,
      },
      {
        name: 'Proyecto',
        math: 85,
        science: 90,
        spanish: 78,
        english: 88,
        history: 89,
      },
      {
        name: 'Tarea 1',
        math: 82,
        science: 91,
        spanish: 76,
        english: 86,
        history: 88,
      },
      {
        name: 'Examen 2',
        math: 86,
        science: 93,
        spanish: 79,
        english: 89,
        history: 91,
      },
    ],
  },

  {
    id: 3,
    name: 'María Rodríguez',
    email: 'maria.rodriguez@escuela.com',
    avatar: 'MR',
    currentGrades: {
      math: 92,
      science: 89,
      spanish: 95,
      english: 91,
      history: 87,
    },
    monthlyProgress: [
      {
        month: 'Ene',
        math: 88,
        science: 85,
        spanish: 92,
        english: 88,
        history: 84,
      },
      {
        month: 'Feb',
        math: 89,
        science: 86,
        spanish: 93,
        english: 89,
        history: 85,
      },
      {
        month: 'Mar',
        math: 90,
        science: 87,
        spanish: 94,
        english: 90,
        history: 86,
      },
      {
        month: 'Abr',
        math: 91,
        science: 88,
        spanish: 95,
        english: 91,
        history: 87,
      },
      {
        month: 'May',
        math: 92,
        science: 89,
        spanish: 95,
        english: 91,
        history: 87,
      },
    ],
    assignments: [
      {
        name: 'Examen 1',
        math: 94,
        science: 91,
        spanish: 97,
        english: 93,
        history: 89,
      },
      {
        name: 'Proyecto',
        math: 92,
        science: 89,
        spanish: 95,
        english: 91,
        history: 87,
      },
      {
        name: 'Tarea 1',
        math: 90,
        science: 87,
        spanish: 93,
        english: 89,
        history: 85,
      },
      {
        name: 'Examen 2',
        math: 93,
        science: 90,
        spanish: 96,
        english: 92,
        history: 88,
      },
    ],
  },
  {
    id: 4,
    name: 'Diego Martín',
    email: 'diego.martin@escuela.com',
    avatar: 'DM',
    currentGrades: {
      math: 88,
      science: 91,
      spanish: 85,
      english: 89,
      history: 92,
    },
    monthlyProgress: [
      {
        month: 'Ene',
        math: 85,
        science: 88,
        spanish: 82,
        english: 86,
        history: 89,
      },
      {
        month: 'Feb',
        math: 86,
        science: 89,
        spanish: 83,
        english: 87,
        history: 90,
      },
      {
        month: 'Mar',
        math: 87,
        science: 90,
        spanish: 84,
        english: 88,
        history: 91,
      },
      {
        month: 'Abr',
        math: 88,
        science: 91,
        spanish: 85,
        english: 89,
        history: 92,
      },
      {
        month: 'May',
        math: 88,
        science: 91,
        spanish: 85,
        english: 89,
        history: 92,
      },
    ],
    assignments: [
      {
        name: 'Examen 1',
        math: 90,
        science: 93,
        spanish: 87,
        english: 91,
        history: 94,
      },
      {
        name: 'Proyecto',
        math: 88,
        science: 91,
        spanish: 85,
        english: 89,
        history: 92,
      },
      {
        name: 'Tarea 1',
        math: 86,
        science: 89,
        spanish: 83,
        english: 87,
        history: 90,
      },
      {
        name: 'Examen 2',
        math: 89,
        science: 92,
        spanish: 86,
        english: 90,
        history: 93,
      },
    ],
  },
  {
    id: 5,
    name: 'Sofía Hernández',
    email: 'sofia.hernandez@escuela.com',
    avatar: 'SH',
    currentGrades: {
      math: 95,
      science: 88,
      spanish: 90,
      english: 93,
      history: 89,
    },
    monthlyProgress: [
      {
        month: 'Ene',
        math: 92,
        science: 85,
        spanish: 87,
        english: 90,
        history: 86,
      },
      {
        month: 'Feb',
        math: 93,
        science: 86,
        spanish: 88,
        english: 91,
        history: 87,
      },
      {
        month: 'Mar',
        math: 94,
        science: 87,
        spanish: 89,
        english: 92,
        history: 88,
      },
      {
        month: 'Abr',
        math: 95,
        science: 88,
        spanish: 90,
        english: 93,
        history: 89,
      },
      {
        month: 'May',
        math: 95,
        science: 88,
        spanish: 90,
        english: 93,
        history: 89,
      },
    ],
    assignments: [
      {
        name: 'Examen 1',
        math: 97,
        science: 90,
        spanish: 92,
        english: 95,
        history: 91,
      },
      {
        name: 'Proyecto',
        math: 95,
        science: 88,
        spanish: 90,
        english: 93,
        history: 89,
      },
      {
        name: 'Tarea 1',
        math: 93,
        science: 86,
        spanish: 88,
        english: 91,
        history: 87,
      },
      {
        name: 'Examen 2',
        math: 96,
        science: 89,
        spanish: 91,
        english: 94,
        history: 90,
      },
    ],
  },
  {
    id: 6,
    name: 'Javier Ruiz',
    email: 'javier.ruiz@escuela.com',
    avatar: 'JR',
    currentGrades: {
      math: 82,
      science: 86,
      spanish: 88,
      english: 84,
      history: 91,
    },
    monthlyProgress: [
      {
        month: 'Ene',
        math: 79,
        science: 83,
        spanish: 85,
        english: 81,
        history: 88,
      },
      {
        month: 'Feb',
        math: 80,
        science: 84,
        spanish: 86,
        english: 82,
        history: 89,
      },
      {
        month: 'Mar',
        math: 81,
        science: 85,
        spanish: 87,
        english: 83,
        history: 90,
      },
      {
        month: 'Abr',
        math: 82,
        science: 86,
        spanish: 88,
        english: 84,
        history: 91,
      },
      {
        month: 'May',
        math: 82,
        science: 86,
        spanish: 88,
        english: 84,
        history: 91,
      },
    ],
    assignments: [
      {
        name: 'Examen 1',
        math: 84,
        science: 88,
        spanish: 90,
        english: 86,
        history: 93,
      },
      {
        name: 'Proyecto',
        math: 82,
        science: 86,
        spanish: 88,
        english: 84,
        history: 91,
      },
      {
        name: 'Tarea 1',
        math: 80,
        science: 84,
        spanish: 86,
        english: 82,
        history: 89,
      },
      {
        name: 'Examen 2',
        math: 83,
        science: 87,
        spanish: 89,
        english: 85,
        history: 92,
      },
    ],
  },
  {
    id: 1,
    name: 'Ana García',
    email: 'ana.garcia@escuela.com',
    avatar: 'AG',
    currentGrades: {
      math: 85,
      science: 92,
      spanish: 78,
      english: 88,
      history: 90,
    },
    monthlyProgress: [
      {
        month: 'Ene',
        math: 80,
        science: 88,
        spanish: 75,
        english: 85,
        history: 87,
      },
      {
        month: 'Feb',
        math: 82,
        science: 89,
        spanish: 76,
        english: 86,
        history: 88,
      },
      {
        month: 'Mar',
        math: 84,
        science: 90,
        spanish: 77,
        english: 87,
        history: 89,
      },
      {
        month: 'Abr',
        math: 85,
        science: 91,
        spanish: 78,
        english: 88,
        history: 90,
      },
      {
        month: 'May',
        math: 85,
        science: 92,
        spanish: 78,
        english: 88,
        history: 90,
      },
    ],
    assignments: [
      {
        name: 'Examen 1',
        math: 88,
        science: 95,
        spanish: 80,
        english: 90,
        history: 92,
      },
      {
        name: 'Proyecto',
        math: 85,
        science: 90,
        spanish: 78,
        english: 88,
        history: 89,
      },
      {
        name: 'Tarea 1',
        math: 82,
        science: 91,
        spanish: 76,
        english: 86,
        history: 88,
      },
      {
        name: 'Examen 2',
        math: 86,
        science: 93,
        spanish: 79,
        english: 89,
        history: 91,
      },
    ],
  },

  {
    id: 3,
    name: 'María Rodríguez',
    email: 'maria.rodriguez@escuela.com',
    avatar: 'MR',
    currentGrades: {
      math: 92,
      science: 89,
      spanish: 95,
      english: 91,
      history: 87,
    },
    monthlyProgress: [
      {
        month: 'Ene',
        math: 88,
        science: 85,
        spanish: 92,
        english: 88,
        history: 84,
      },
      {
        month: 'Feb',
        math: 89,
        science: 86,
        spanish: 93,
        english: 89,
        history: 85,
      },
      {
        month: 'Mar',
        math: 90,
        science: 87,
        spanish: 94,
        english: 90,
        history: 86,
      },
      {
        month: 'Abr',
        math: 91,
        science: 88,
        spanish: 95,
        english: 91,
        history: 87,
      },
      {
        month: 'May',
        math: 92,
        science: 89,
        spanish: 95,
        english: 91,
        history: 87,
      },
    ],
    assignments: [
      {
        name: 'Examen 1',
        math: 94,
        science: 91,
        spanish: 97,
        english: 93,
        history: 89,
      },
      {
        name: 'Proyecto',
        math: 92,
        science: 89,
        spanish: 95,
        english: 91,
        history: 87,
      },
      {
        name: 'Tarea 1',
        math: 90,
        science: 87,
        spanish: 93,
        english: 89,
        history: 85,
      },
      {
        name: 'Examen 2',
        math: 93,
        science: 90,
        spanish: 96,
        english: 92,
        history: 88,
      },
    ],
  },
  {
    id: 4,
    name: 'Diego Martín',
    email: 'diego.martin@escuela.com',
    avatar: 'DM',
    currentGrades: {
      math: 88,
      science: 91,
      spanish: 85,
      english: 89,
      history: 92,
    },
    monthlyProgress: [
      {
        month: 'Ene',
        math: 85,
        science: 88,
        spanish: 82,
        english: 86,
        history: 89,
      },
      {
        month: 'Feb',
        math: 86,
        science: 89,
        spanish: 83,
        english: 87,
        history: 90,
      },
      {
        month: 'Mar',
        math: 87,
        science: 90,
        spanish: 84,
        english: 88,
        history: 91,
      },
      {
        month: 'Abr',
        math: 88,
        science: 91,
        spanish: 85,
        english: 89,
        history: 92,
      },
      {
        month: 'May',
        math: 88,
        science: 91,
        spanish: 85,
        english: 89,
        history: 92,
      },
    ],
    assignments: [
      {
        name: 'Examen 1',
        math: 90,
        science: 93,
        spanish: 87,
        english: 91,
        history: 94,
      },
      {
        name: 'Proyecto',
        math: 88,
        science: 91,
        spanish: 85,
        english: 89,
        history: 92,
      },
      {
        name: 'Tarea 1',
        math: 86,
        science: 89,
        spanish: 83,
        english: 87,
        history: 90,
      },
      {
        name: 'Examen 2',
        math: 89,
        science: 92,
        spanish: 86,
        english: 90,
        history: 93,
      },
    ],
  },
  {
    id: 5,
    name: 'Sofía Hernández',
    email: 'sofia.hernandez@escuela.com',
    avatar: 'SH',
    currentGrades: {
      math: 95,
      science: 88,
      spanish: 90,
      english: 93,
      history: 89,
    },
    monthlyProgress: [
      {
        month: 'Ene',
        math: 92,
        science: 85,
        spanish: 87,
        english: 90,
        history: 86,
      },
      {
        month: 'Feb',
        math: 93,
        science: 86,
        spanish: 88,
        english: 91,
        history: 87,
      },
      {
        month: 'Mar',
        math: 94,
        science: 87,
        spanish: 89,
        english: 92,
        history: 88,
      },
      {
        month: 'Abr',
        math: 95,
        science: 88,
        spanish: 90,
        english: 93,
        history: 89,
      },
      {
        month: 'May',
        math: 95,
        science: 88,
        spanish: 90,
        english: 93,
        history: 89,
      },
    ],
    assignments: [
      {
        name: 'Examen 1',
        math: 97,
        science: 90,
        spanish: 92,
        english: 95,
        history: 91,
      },
      {
        name: 'Proyecto',
        math: 95,
        science: 88,
        spanish: 90,
        english: 93,
        history: 89,
      },
      {
        name: 'Tarea 1',
        math: 93,
        science: 86,
        spanish: 88,
        english: 91,
        history: 87,
      },
      {
        name: 'Examen 2',
        math: 96,
        science: 89,
        spanish: 91,
        english: 94,
        history: 90,
      },
    ],
  },
  {
    id: 6,
    name: 'Javier Ruiz',
    email: 'javier.ruiz@escuela.com',
    avatar: 'JR',
    currentGrades: {
      math: 82,
      science: 86,
      spanish: 88,
      english: 84,
      history: 91,
    },
    monthlyProgress: [
      {
        month: 'Ene',
        math: 79,
        science: 83,
        spanish: 85,
        english: 81,
        history: 88,
      },
      {
        month: 'Feb',
        math: 80,
        science: 84,
        spanish: 86,
        english: 82,
        history: 89,
      },
      {
        month: 'Mar',
        math: 81,
        science: 85,
        spanish: 87,
        english: 83,
        history: 90,
      },
      {
        month: 'Abr',
        math: 82,
        science: 86,
        spanish: 88,
        english: 84,
        history: 91,
      },
      {
        month: 'May',
        math: 82,
        science: 86,
        spanish: 88,
        english: 84,
        history: 91,
      },
    ],
    assignments: [
      {
        name: 'Examen 1',
        math: 84,
        science: 88,
        spanish: 90,
        english: 86,
        history: 93,
      },
      {
        name: 'Proyecto',
        math: 82,
        science: 86,
        spanish: 88,
        english: 84,
        history: 91,
      },
      {
        name: 'Tarea 1',
        math: 80,
        science: 84,
        spanish: 86,
        english: 82,
        history: 89,
      },
      {
        name: 'Examen 2',
        math: 83,
        science: 87,
        spanish: 89,
        english: 85,
        history: 92,
      },
    ],
  },
  {
    id: 1,
    name: 'Ana García',
    email: 'ana.garcia@escuela.com',
    avatar: 'AG',
    currentGrades: {
      math: 85,
      science: 92,
      spanish: 78,
      english: 88,
      history: 90,
    },
    monthlyProgress: [
      {
        month: 'Ene',
        math: 80,
        science: 88,
        spanish: 75,
        english: 85,
        history: 87,
      },
      {
        month: 'Feb',
        math: 82,
        science: 89,
        spanish: 76,
        english: 86,
        history: 88,
      },
      {
        month: 'Mar',
        math: 84,
        science: 90,
        spanish: 77,
        english: 87,
        history: 89,
      },
      {
        month: 'Abr',
        math: 85,
        science: 91,
        spanish: 78,
        english: 88,
        history: 90,
      },
      {
        month: 'May',
        math: 85,
        science: 92,
        spanish: 78,
        english: 88,
        history: 90,
      },
    ],
    assignments: [
      {
        name: 'Examen 1',
        math: 88,
        science: 95,
        spanish: 80,
        english: 90,
        history: 92,
      },
      {
        name: 'Proyecto',
        math: 85,
        science: 90,
        spanish: 78,
        english: 88,
        history: 89,
      },
      {
        name: 'Tarea 1',
        math: 82,
        science: 91,
        spanish: 76,
        english: 86,
        history: 88,
      },
      {
        name: 'Examen 2',
        math: 86,
        science: 93,
        spanish: 79,
        english: 89,
        history: 91,
      },
    ],
  },
  {
    id: 2,
    name: 'Carlos López',
    email: 'carlos.lopez@escuela.com',
    avatar: 'CL',
    currentGrades: {
      math: 78,
      science: 85,
      spanish: 82,
      english: 75,
      history: 88,
    },
    monthlyProgress: [
      {
        month: 'Ene',
        math: 75,
        science: 82,
        spanish: 80,
        english: 72,
        history: 85,
      },
      {
        month: 'Feb',
        math: 76,
        science: 83,
        spanish: 81,
        english: 73,
        history: 86,
      },
      {
        month: 'Mar',
        math: 77,
        science: 84,
        spanish: 82,
        english: 74,
        history: 87,
      },
      {
        month: 'Abr',
        math: 78,
        science: 85,
        spanish: 82,
        english: 75,
        history: 88,
      },
      {
        month: 'May',
        math: 78,
        science: 85,
        spanish: 82,
        english: 75,
        history: 88,
      },
    ],
    assignments: [
      {
        name: 'Examen 1',
        math: 80,
        science: 87,
        spanish: 84,
        english: 77,
        history: 90,
      },
      {
        name: 'Proyecto',
        math: 78,
        science: 85,
        spanish: 82,
        english: 75,
        history: 88,
      },
      {
        name: 'Tarea 1',
        math: 76,
        science: 83,
        spanish: 80,
        english: 73,
        history: 86,
      },
      {
        name: 'Examen 2',
        math: 79,
        science: 86,
        spanish: 83,
        english: 76,
        history: 89,
      },
    ],
  },
  {
    id: 3,
    name: 'María Rodríguez',
    email: 'maria.rodriguez@escuela.com',
    avatar: 'MR',
    currentGrades: {
      math: 92,
      science: 89,
      spanish: 95,
      english: 91,
      history: 87,
    },
    monthlyProgress: [
      {
        month: 'Ene',
        math: 88,
        science: 85,
        spanish: 92,
        english: 88,
        history: 84,
      },
      {
        month: 'Feb',
        math: 89,
        science: 86,
        spanish: 93,
        english: 89,
        history: 85,
      },
      {
        month: 'Mar',
        math: 90,
        science: 87,
        spanish: 94,
        english: 90,
        history: 86,
      },
      {
        month: 'Abr',
        math: 91,
        science: 88,
        spanish: 95,
        english: 91,
        history: 87,
      },
      {
        month: 'May',
        math: 92,
        science: 89,
        spanish: 95,
        english: 91,
        history: 87,
      },
    ],
    assignments: [
      {
        name: 'Examen 1',
        math: 94,
        science: 91,
        spanish: 97,
        english: 93,
        history: 89,
      },
      {
        name: 'Proyecto',
        math: 92,
        science: 89,
        spanish: 95,
        english: 91,
        history: 87,
      },
      {
        name: 'Tarea 1',
        math: 90,
        science: 87,
        spanish: 93,
        english: 89,
        history: 85,
      },
      {
        name: 'Examen 2',
        math: 93,
        science: 90,
        spanish: 96,
        english: 92,
        history: 88,
      },
    ],
  },
  {
    id: 4,
    name: 'Diego Martín',
    email: 'diego.martin@escuela.com',
    avatar: 'DM',
    currentGrades: {
      math: 88,
      science: 91,
      spanish: 85,
      english: 89,
      history: 92,
    },
    monthlyProgress: [
      {
        month: 'Ene',
        math: 85,
        science: 88,
        spanish: 82,
        english: 86,
        history: 89,
      },
      {
        month: 'Feb',
        math: 86,
        science: 89,
        spanish: 83,
        english: 87,
        history: 90,
      },
      {
        month: 'Mar',
        math: 87,
        science: 90,
        spanish: 84,
        english: 88,
        history: 91,
      },
      {
        month: 'Abr',
        math: 88,
        science: 91,
        spanish: 85,
        english: 89,
        history: 92,
      },
      {
        month: 'May',
        math: 88,
        science: 91,
        spanish: 85,
        english: 89,
        history: 92,
      },
    ],
    assignments: [
      {
        name: 'Examen 1',
        math: 90,
        science: 93,
        spanish: 87,
        english: 91,
        history: 94,
      },
      {
        name: 'Proyecto',
        math: 88,
        science: 91,
        spanish: 85,
        english: 89,
        history: 92,
      },
      {
        name: 'Tarea 1',
        math: 86,
        science: 89,
        spanish: 83,
        english: 87,
        history: 90,
      },
      {
        name: 'Examen 2',
        math: 89,
        science: 92,
        spanish: 86,
        english: 90,
        history: 93,
      },
    ],
  },
  {
    id: 5,
    name: 'Sofía Hernández',
    email: 'sofia.hernandez@escuela.com',
    avatar: 'SH',
    currentGrades: {
      math: 95,
      science: 88,
      spanish: 90,
      english: 93,
      history: 89,
    },
    monthlyProgress: [
      {
        month: 'Ene',
        math: 92,
        science: 85,
        spanish: 87,
        english: 90,
        history: 86,
      },
      {
        month: 'Feb',
        math: 93,
        science: 86,
        spanish: 88,
        english: 91,
        history: 87,
      },
      {
        month: 'Mar',
        math: 94,
        science: 87,
        spanish: 89,
        english: 92,
        history: 88,
      },
      {
        month: 'Abr',
        math: 95,
        science: 88,
        spanish: 90,
        english: 93,
        history: 89,
      },
      {
        month: 'May',
        math: 95,
        science: 88,
        spanish: 90,
        english: 93,
        history: 89,
      },
    ],
    assignments: [
      {
        name: 'Examen 1',
        math: 97,
        science: 90,
        spanish: 92,
        english: 95,
        history: 91,
      },
      {
        name: 'Proyecto',
        math: 95,
        science: 88,
        spanish: 90,
        english: 93,
        history: 89,
      },
      {
        name: 'Tarea 1',
        math: 93,
        science: 86,
        spanish: 88,
        english: 91,
        history: 87,
      },
      {
        name: 'Examen 2',
        math: 96,
        science: 89,
        spanish: 91,
        english: 94,
        history: 90,
      },
    ],
  },
  {
    id: 6,
    name: 'Javier Ruiz',
    email: 'javier.ruiz@escuela.com',
    avatar: 'JR',
    currentGrades: {
      math: 82,
      science: 86,
      spanish: 88,
      english: 84,
      history: 91,
    },
    monthlyProgress: [
      {
        month: 'Ene',
        math: 79,
        science: 83,
        spanish: 85,
        english: 81,
        history: 88,
      },
      {
        month: 'Feb',
        math: 80,
        science: 84,
        spanish: 86,
        english: 82,
        history: 89,
      },
      {
        month: 'Mar',
        math: 81,
        science: 85,
        spanish: 87,
        english: 83,
        history: 90,
      },
      {
        month: 'Abr',
        math: 82,
        science: 86,
        spanish: 88,
        english: 84,
        history: 91,
      },
      {
        month: 'May',
        math: 82,
        science: 86,
        spanish: 88,
        english: 84,
        history: 91,
      },
    ],
    assignments: [
      {
        name: 'Examen 1',
        math: 84,
        science: 88,
        spanish: 90,
        english: 86,
        history: 93,
      },
      {
        name: 'Proyecto',
        math: 82,
        science: 86,
        spanish: 88,
        english: 84,
        history: 91,
      },
      {
        name: 'Tarea 1',
        math: 80,
        science: 84,
        spanish: 86,
        english: 82,
        history: 89,
      },
      {
        name: 'Examen 2',
        math: 83,
        science: 87,
        spanish: 89,
        english: 85,
        history: 92,
      },
    ],
  },
  {
    id: 1,
    name: 'Ana García',
    email: 'ana.garcia@escuela.com',
    avatar: 'AG',
    currentGrades: {
      math: 85,
      science: 92,
      spanish: 78,
      english: 88,
      history: 90,
    },
    monthlyProgress: [
      {
        month: 'Ene',
        math: 80,
        science: 88,
        spanish: 75,
        english: 85,
        history: 87,
      },
      {
        month: 'Feb',
        math: 82,
        science: 89,
        spanish: 76,
        english: 86,
        history: 88,
      },
      {
        month: 'Mar',
        math: 84,
        science: 90,
        spanish: 77,
        english: 87,
        history: 89,
      },
      {
        month: 'Abr',
        math: 85,
        science: 91,
        spanish: 78,
        english: 88,
        history: 90,
      },
      {
        month: 'May',
        math: 85,
        science: 92,
        spanish: 78,
        english: 88,
        history: 90,
      },
    ],
    assignments: [
      {
        name: 'Examen 1',
        math: 88,
        science: 95,
        spanish: 80,
        english: 90,
        history: 92,
      },
      {
        name: 'Proyecto',
        math: 85,
        science: 90,
        spanish: 78,
        english: 88,
        history: 89,
      },
      {
        name: 'Tarea 1',
        math: 82,
        science: 91,
        spanish: 76,
        english: 86,
        history: 88,
      },
      {
        name: 'Examen 2',
        math: 86,
        science: 93,
        spanish: 79,
        english: 89,
        history: 91,
      },
    ],
  },
  {
    id: 2,
    name: 'Carlos López',
    email: 'carlos.lopez@escuela.com',
    avatar: 'CL',
    currentGrades: {
      math: 78,
      science: 85,
      spanish: 82,
      english: 75,
      history: 88,
    },
    monthlyProgress: [
      {
        month: 'Ene',
        math: 75,
        science: 82,
        spanish: 80,
        english: 72,
        history: 85,
      },
      {
        month: 'Feb',
        math: 76,
        science: 83,
        spanish: 81,
        english: 73,
        history: 86,
      },
      {
        month: 'Mar',
        math: 77,
        science: 84,
        spanish: 82,
        english: 74,
        history: 87,
      },
      {
        month: 'Abr',
        math: 78,
        science: 85,
        spanish: 82,
        english: 75,
        history: 88,
      },
      {
        month: 'May',
        math: 78,
        science: 85,
        spanish: 82,
        english: 75,
        history: 88,
      },
    ],
    assignments: [
      {
        name: 'Examen 1',
        math: 80,
        science: 87,
        spanish: 84,
        english: 77,
        history: 90,
      },
      {
        name: 'Proyecto',
        math: 78,
        science: 85,
        spanish: 82,
        english: 75,
        history: 88,
      },
      {
        name: 'Tarea 1',
        math: 76,
        science: 83,
        spanish: 80,
        english: 73,
        history: 86,
      },
      {
        name: 'Examen 2',
        math: 79,
        science: 86,
        spanish: 83,
        english: 76,
        history: 89,
      },
    ],
  },
  {
    id: 3,
    name: 'María Rodríguez',
    email: 'maria.rodriguez@escuela.com',
    avatar: 'MR',
    currentGrades: {
      math: 92,
      science: 89,
      spanish: 95,
      english: 91,
      history: 87,
    },
    monthlyProgress: [
      {
        month: 'Ene',
        math: 88,
        science: 85,
        spanish: 92,
        english: 88,
        history: 84,
      },
      {
        month: 'Feb',
        math: 89,
        science: 86,
        spanish: 93,
        english: 89,
        history: 85,
      },
      {
        month: 'Mar',
        math: 90,
        science: 87,
        spanish: 94,
        english: 90,
        history: 86,
      },
      {
        month: 'Abr',
        math: 91,
        science: 88,
        spanish: 95,
        english: 91,
        history: 87,
      },
      {
        month: 'May',
        math: 92,
        science: 89,
        spanish: 95,
        english: 91,
        history: 87,
      },
    ],
    assignments: [
      {
        name: 'Examen 1',
        math: 94,
        science: 91,
        spanish: 97,
        english: 93,
        history: 89,
      },
      {
        name: 'Proyecto',
        math: 92,
        science: 89,
        spanish: 95,
        english: 91,
        history: 87,
      },
      {
        name: 'Tarea 1',
        math: 90,
        science: 87,
        spanish: 93,
        english: 89,
        history: 85,
      },
      {
        name: 'Examen 2',
        math: 93,
        science: 90,
        spanish: 96,
        english: 92,
        history: 88,
      },
    ],
  },
  {
    id: 4,
    name: 'Diego Martín',
    email: 'diego.martin@escuela.com',
    avatar: 'DM',
    currentGrades: {
      math: 88,
      science: 91,
      spanish: 85,
      english: 89,
      history: 92,
    },
    monthlyProgress: [
      {
        month: 'Ene',
        math: 85,
        science: 88,
        spanish: 82,
        english: 86,
        history: 89,
      },
      {
        month: 'Feb',
        math: 86,
        science: 89,
        spanish: 83,
        english: 87,
        history: 90,
      },
      {
        month: 'Mar',
        math: 87,
        science: 90,
        spanish: 84,
        english: 88,
        history: 91,
      },
      {
        month: 'Abr',
        math: 88,
        science: 91,
        spanish: 85,
        english: 89,
        history: 92,
      },
      {
        month: 'May',
        math: 88,
        science: 91,
        spanish: 85,
        english: 89,
        history: 92,
      },
    ],
    assignments: [
      {
        name: 'Examen 1',
        math: 90,
        science: 93,
        spanish: 87,
        english: 91,
        history: 94,
      },
      {
        name: 'Proyecto',
        math: 88,
        science: 91,
        spanish: 85,
        english: 89,
        history: 92,
      },
      {
        name: 'Tarea 1',
        math: 86,
        science: 89,
        spanish: 83,
        english: 87,
        history: 90,
      },
      {
        name: 'Examen 2',
        math: 89,
        science: 92,
        spanish: 86,
        english: 90,
        history: 93,
      },
    ],
  },
  {
    id: 5,
    name: 'Sofía Hernández',
    email: 'sofia.hernandez@escuela.com',
    avatar: 'SH',
    currentGrades: {
      math: 95,
      science: 88,
      spanish: 90,
      english: 93,
      history: 89,
    },
    monthlyProgress: [
      {
        month: 'Ene',
        math: 92,
        science: 85,
        spanish: 87,
        english: 90,
        history: 86,
      },
      {
        month: 'Feb',
        math: 93,
        science: 86,
        spanish: 88,
        english: 91,
        history: 87,
      },
      {
        month: 'Mar',
        math: 94,
        science: 87,
        spanish: 89,
        english: 92,
        history: 88,
      },
      {
        month: 'Abr',
        math: 95,
        science: 88,
        spanish: 90,
        english: 93,
        history: 89,
      },
      {
        month: 'May',
        math: 95,
        science: 88,
        spanish: 90,
        english: 93,
        history: 89,
      },
    ],
    assignments: [
      {
        name: 'Examen 1',
        math: 97,
        science: 90,
        spanish: 92,
        english: 95,
        history: 91,
      },
      {
        name: 'Proyecto',
        math: 95,
        science: 88,
        spanish: 90,
        english: 93,
        history: 89,
      },
      {
        name: 'Tarea 1',
        math: 93,
        science: 86,
        spanish: 88,
        english: 91,
        history: 87,
      },
      {
        name: 'Examen 2',
        math: 96,
        science: 89,
        spanish: 91,
        english: 94,
        history: 90,
      },
    ],
  },
  {
    id: 6,
    name: 'Javier Ruiz',
    email: 'javier.ruiz@escuela.com',
    avatar: 'JR',
    currentGrades: {
      math: 82,
      science: 86,
      spanish: 88,
      english: 84,
      history: 91,
    },
    monthlyProgress: [
      {
        month: 'Ene',
        math: 79,
        science: 83,
        spanish: 85,
        english: 81,
        history: 88,
      },
      {
        month: 'Feb',
        math: 80,
        science: 84,
        spanish: 86,
        english: 82,
        history: 89,
      },
      {
        month: 'Mar',
        math: 81,
        science: 85,
        spanish: 87,
        english: 83,
        history: 90,
      },
      {
        month: 'Abr',
        math: 82,
        science: 86,
        spanish: 88,
        english: 84,
        history: 91,
      },
      {
        month: 'May',
        math: 82,
        science: 86,
        spanish: 88,
        english: 84,
        history: 91,
      },
    ],
    assignments: [
      {
        name: 'Examen 1',
        math: 84,
        science: 88,
        spanish: 90,
        english: 86,
        history: 93,
      },
      {
        name: 'Proyecto',
        math: 82,
        science: 86,
        spanish: 88,
        english: 84,
        history: 91,
      },
      {
        name: 'Tarea 1',
        math: 80,
        science: 84,
        spanish: 86,
        english: 82,
        history: 89,
      },
      {
        name: 'Examen 2',
        math: 83,
        science: 87,
        spanish: 89,
        english: 85,
        history: 92,
      },
    ],
  },
  {
    id: 1,
    name: 'Ana García',
    email: 'ana.garcia@escuela.com',
    avatar: 'AG',
    currentGrades: {
      math: 85,
      science: 92,
      spanish: 78,
      english: 88,
      history: 90,
    },
    monthlyProgress: [
      {
        month: 'Ene',
        math: 80,
        science: 88,
        spanish: 75,
        english: 85,
        history: 87,
      },
      {
        month: 'Feb',
        math: 82,
        science: 89,
        spanish: 76,
        english: 86,
        history: 88,
      },
      {
        month: 'Mar',
        math: 84,
        science: 90,
        spanish: 77,
        english: 87,
        history: 89,
      },
      {
        month: 'Abr',
        math: 85,
        science: 91,
        spanish: 78,
        english: 88,
        history: 90,
      },
      {
        month: 'May',
        math: 85,
        science: 92,
        spanish: 78,
        english: 88,
        history: 90,
      },
    ],
    assignments: [
      {
        name: 'Examen 1',
        math: 88,
        science: 95,
        spanish: 80,
        english: 90,
        history: 92,
      },
      {
        name: 'Proyecto',
        math: 85,
        science: 90,
        spanish: 78,
        english: 88,
        history: 89,
      },
      {
        name: 'Tarea 1',
        math: 82,
        science: 91,
        spanish: 76,
        english: 86,
        history: 88,
      },
      {
        name: 'Examen 2',
        math: 86,
        science: 93,
        spanish: 79,
        english: 89,
        history: 91,
      },
    ],
  },
  {
    id: 2,
    name: 'Carlos López',
    email: 'carlos.lopez@escuela.com',
    avatar: 'CL',
    currentGrades: {
      math: 78,
      science: 85,
      spanish: 82,
      english: 75,
      history: 88,
    },
    monthlyProgress: [
      {
        month: 'Ene',
        math: 75,
        science: 82,
        spanish: 80,
        english: 72,
        history: 85,
      },
      {
        month: 'Feb',
        math: 76,
        science: 83,
        spanish: 81,
        english: 73,
        history: 86,
      },
      {
        month: 'Mar',
        math: 77,
        science: 84,
        spanish: 82,
        english: 74,
        history: 87,
      },
      {
        month: 'Abr',
        math: 78,
        science: 85,
        spanish: 82,
        english: 75,
        history: 88,
      },
      {
        month: 'May',
        math: 78,
        science: 85,
        spanish: 82,
        english: 75,
        history: 88,
      },
    ],
    assignments: [
      {
        name: 'Examen 1',
        math: 80,
        science: 87,
        spanish: 84,
        english: 77,
        history: 90,
      },
      {
        name: 'Proyecto',
        math: 78,
        science: 85,
        spanish: 82,
        english: 75,
        history: 88,
      },
      {
        name: 'Tarea 1',
        math: 76,
        science: 83,
        spanish: 80,
        english: 73,
        history: 86,
      },
      {
        name: 'Examen 2',
        math: 79,
        science: 86,
        spanish: 83,
        english: 76,
        history: 89,
      },
    ],
  },
  {
    id: 3,
    name: 'María Rodríguez',
    email: 'maria.rodriguez@escuela.com',
    avatar: 'MR',
    currentGrades: {
      math: 92,
      science: 89,
      spanish: 95,
      english: 91,
      history: 87,
    },
    monthlyProgress: [
      {
        month: 'Ene',
        math: 88,
        science: 85,
        spanish: 92,
        english: 88,
        history: 84,
      },
      {
        month: 'Feb',
        math: 89,
        science: 86,
        spanish: 93,
        english: 89,
        history: 85,
      },
      {
        month: 'Mar',
        math: 90,
        science: 87,
        spanish: 94,
        english: 90,
        history: 86,
      },
      {
        month: 'Abr',
        math: 91,
        science: 88,
        spanish: 95,
        english: 91,
        history: 87,
      },
      {
        month: 'May',
        math: 92,
        science: 89,
        spanish: 95,
        english: 91,
        history: 87,
      },
    ],
    assignments: [
      {
        name: 'Examen 1',
        math: 94,
        science: 91,
        spanish: 97,
        english: 93,
        history: 89,
      },
      {
        name: 'Proyecto',
        math: 92,
        science: 89,
        spanish: 95,
        english: 91,
        history: 87,
      },
      {
        name: 'Tarea 1',
        math: 90,
        science: 87,
        spanish: 93,
        english: 89,
        history: 85,
      },
      {
        name: 'Examen 2',
        math: 93,
        science: 90,
        spanish: 96,
        english: 92,
        history: 88,
      },
    ],
  },
  {
    id: 4,
    name: 'Diego Martín',
    email: 'diego.martin@escuela.com',
    avatar: 'DM',
    currentGrades: {
      math: 88,
      science: 91,
      spanish: 85,
      english: 89,
      history: 92,
    },
    monthlyProgress: [
      {
        month: 'Ene',
        math: 85,
        science: 88,
        spanish: 82,
        english: 86,
        history: 89,
      },
      {
        month: 'Feb',
        math: 86,
        science: 89,
        spanish: 83,
        english: 87,
        history: 90,
      },
      {
        month: 'Mar',
        math: 87,
        science: 90,
        spanish: 84,
        english: 88,
        history: 91,
      },
      {
        month: 'Abr',
        math: 88,
        science: 91,
        spanish: 85,
        english: 89,
        history: 92,
      },
      {
        month: 'May',
        math: 88,
        science: 91,
        spanish: 85,
        english: 89,
        history: 92,
      },
    ],
    assignments: [
      {
        name: 'Examen 1',
        math: 90,
        science: 93,
        spanish: 87,
        english: 91,
        history: 94,
      },
      {
        name: 'Proyecto',
        math: 88,
        science: 91,
        spanish: 85,
        english: 89,
        history: 92,
      },
      {
        name: 'Tarea 1',
        math: 86,
        science: 89,
        spanish: 83,
        english: 87,
        history: 90,
      },
      {
        name: 'Examen 2',
        math: 89,
        science: 92,
        spanish: 86,
        english: 90,
        history: 93,
      },
    ],
  },
  {
    id: 5,
    name: 'Sofía Hernández',
    email: 'sofia.hernandez@escuela.com',
    avatar: 'SH',
    currentGrades: {
      math: 95,
      science: 88,
      spanish: 90,
      english: 93,
      history: 89,
    },
    monthlyProgress: [
      {
        month: 'Ene',
        math: 92,
        science: 85,
        spanish: 87,
        english: 90,
        history: 86,
      },
      {
        month: 'Feb',
        math: 93,
        science: 86,
        spanish: 88,
        english: 91,
        history: 87,
      },
      {
        month: 'Mar',
        math: 94,
        science: 87,
        spanish: 89,
        english: 92,
        history: 88,
      },
      {
        month: 'Abr',
        math: 95,
        science: 88,
        spanish: 90,
        english: 93,
        history: 89,
      },
      {
        month: 'May',
        math: 95,
        science: 88,
        spanish: 90,
        english: 93,
        history: 89,
      },
    ],
    assignments: [
      {
        name: 'Examen 1',
        math: 97,
        science: 90,
        spanish: 92,
        english: 95,
        history: 91,
      },
      {
        name: 'Proyecto',
        math: 95,
        science: 88,
        spanish: 90,
        english: 93,
        history: 89,
      },
      {
        name: 'Tarea 1',
        math: 93,
        science: 86,
        spanish: 88,
        english: 91,
        history: 87,
      },
      {
        name: 'Examen 2',
        math: 96,
        science: 89,
        spanish: 91,
        english: 94,
        history: 90,
      },
    ],
  },
  {
    id: 6,
    name: 'Javier Ruiz',
    email: 'javier.ruiz@escuela.com',
    avatar: 'JR',
    currentGrades: {
      math: 82,
      science: 86,
      spanish: 88,
      english: 84,
      history: 91,
    },
    monthlyProgress: [
      {
        month: 'Ene',
        math: 79,
        science: 83,
        spanish: 85,
        english: 81,
        history: 88,
      },
      {
        month: 'Feb',
        math: 80,
        science: 84,
        spanish: 86,
        english: 82,
        history: 89,
      },
      {
        month: 'Mar',
        math: 81,
        science: 85,
        spanish: 87,
        english: 83,
        history: 90,
      },
      {
        month: 'Abr',
        math: 82,
        science: 86,
        spanish: 88,
        english: 84,
        history: 91,
      },
      {
        month: 'May',
        math: 82,
        science: 86,
        spanish: 88,
        english: 84,
        history: 91,
      },
    ],
    assignments: [
      {
        name: 'Examen 1',
        math: 84,
        science: 88,
        spanish: 90,
        english: 86,
        history: 93,
      },
      {
        name: 'Proyecto',
        math: 82,
        science: 86,
        spanish: 88,
        english: 84,
        history: 91,
      },
      {
        name: 'Tarea 1',
        math: 80,
        science: 84,
        spanish: 86,
        english: 82,
        history: 89,
      },
      {
        name: 'Examen 2',
        math: 83,
        science: 87,
        spanish: 89,
        english: 85,
        history: 92,
      },
    ],
  },
];
